-- SPDX-License-Identifier: GPL-3.0-or-later
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;
CREATE TABLE IF NOT EXISTS ops_settings (name TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ops_customers (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_resources (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, technician_id TEXT NOT NULL UNIQUE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_products (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, sku TEXT NOT NULL UNIQUE, stock INTEGER NOT NULL CHECK(stock>=0), reserved INTEGER NOT NULL DEFAULT 0 CHECK(reserved>=0 AND reserved<=stock), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_quotes (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, customer_id INTEGER NOT NULL REFERENCES ops_customers(id), status TEXT NOT NULL CHECK(status IN ('draft','sent','accepted','rejected')), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_workorders (id INTEGER PRIMARY KEY, version INTEGER NOT NULL, quote_id INTEGER NOT NULL UNIQUE REFERENCES ops_quotes(id), customer_id INTEGER NOT NULL REFERENCES ops_customers(id), resource_id INTEGER REFERENCES ops_resources(id), start_at TEXT, end_at TEXT, status TEXT NOT NULL CHECK(status IN ('planned','active','done','cancelled')), data TEXT NOT NULL CHECK(json_valid(data)), CHECK((start_at IS NULL AND end_at IS NULL) OR (start_at IS NOT NULL AND end_at IS NOT NULL AND end_at>start_at)));
CREATE INDEX IF NOT EXISTS ops_workorders_planning ON ops_workorders(resource_id,start_at,end_at);
CREATE TABLE IF NOT EXISTS ops_reservations (workorder_id INTEGER NOT NULL REFERENCES ops_workorders(id), product_id INTEGER NOT NULL REFERENCES ops_products(id), quantity INTEGER NOT NULL CHECK(quantity>0), PRIMARY KEY(workorder_id,product_id));
CREATE TABLE IF NOT EXISTS ops_hours (id INTEGER PRIMARY KEY, workorder_id INTEGER NOT NULL REFERENCES ops_workorders(id), technician_id TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_movements (id INTEGER PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES ops_products(id), workorder_id INTEGER REFERENCES ops_workorders(id), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_invoices (id INTEGER PRIMARY KEY, quote_id INTEGER NOT NULL UNIQUE REFERENCES ops_quotes(id), customer_id INTEGER NOT NULL REFERENCES ops_customers(id), workorder_id INTEGER REFERENCES ops_workorders(id), number TEXT NOT NULL UNIQUE, total_cents INTEGER NOT NULL CHECK(total_cents>=0), data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_payments (id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES ops_invoices(id), amount_cents INTEGER NOT NULL CHECK(amount_cents>0), reference TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(invoice_id,reference));
CREATE TABLE IF NOT EXISTS ops_credits (id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES ops_invoices(id), amount_cents INTEGER NOT NULL CHECK(amount_cents>0), number TEXT NOT NULL UNIQUE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_sequences (name TEXT NOT NULL, year INTEGER NOT NULL, value INTEGER NOT NULL CHECK(value>0), PRIMARY KEY(name,year));
CREATE TABLE IF NOT EXISTS ops_outbox (id INTEGER PRIMARY KEY, event_type TEXT NOT NULL, entity_id INTEGER NOT NULL, exported_at TEXT, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_audit (id INTEGER PRIMARY KEY, actor_id TEXT NOT NULL, operation TEXT NOT NULL, created_at TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE IF NOT EXISTS ops_idempotency (actor_id TEXT NOT NULL, key TEXT NOT NULL, fingerprint TEXT NOT NULL, response TEXT NOT NULL CHECK(json_valid(response)), PRIMARY KEY(actor_id,key));
CREATE TRIGGER IF NOT EXISTS ops_hours_no_update BEFORE UPDATE ON ops_hours BEGIN SELECT RAISE(ABORT,'immutable hours'); END;
CREATE TRIGGER IF NOT EXISTS ops_hours_no_delete BEFORE DELETE ON ops_hours BEGIN SELECT RAISE(ABORT,'immutable hours'); END;
CREATE TRIGGER IF NOT EXISTS ops_invoices_no_update BEFORE UPDATE ON ops_invoices BEGIN SELECT RAISE(ABORT,'immutable invoices'); END;
CREATE TRIGGER IF NOT EXISTS ops_invoices_no_delete BEFORE DELETE ON ops_invoices BEGIN SELECT RAISE(ABORT,'immutable invoices'); END;
CREATE TRIGGER IF NOT EXISTS ops_payments_no_update BEFORE UPDATE ON ops_payments BEGIN SELECT RAISE(ABORT,'immutable payments'); END;
CREATE TRIGGER IF NOT EXISTS ops_payments_no_delete BEFORE DELETE ON ops_payments BEGIN SELECT RAISE(ABORT,'immutable payments'); END;
CREATE TRIGGER IF NOT EXISTS ops_credits_no_update BEFORE UPDATE ON ops_credits BEGIN SELECT RAISE(ABORT,'immutable credits'); END;
CREATE TRIGGER IF NOT EXISTS ops_credits_no_delete BEFORE DELETE ON ops_credits BEGIN SELECT RAISE(ABORT,'immutable credits'); END;
CREATE TRIGGER IF NOT EXISTS ops_movements_no_update BEFORE UPDATE ON ops_movements BEGIN SELECT RAISE(ABORT,'immutable movements'); END;
CREATE TRIGGER IF NOT EXISTS ops_movements_no_delete BEFORE DELETE ON ops_movements BEGIN SELECT RAISE(ABORT,'immutable movements'); END;
CREATE TRIGGER IF NOT EXISTS ops_audit_no_update BEFORE UPDATE ON ops_audit BEGIN SELECT RAISE(ABORT,'immutable audit'); END;
CREATE TRIGGER IF NOT EXISTS ops_audit_no_delete BEFORE DELETE ON ops_audit BEGIN SELECT RAISE(ABORT,'immutable audit'); END;
